{
  config,
  pkgs,
  ...
}:
{
  # Configure homebridge service
  # Note: config.json is generated by secrets module from homebridge.json.j2 template
  services.homebridgeNix = {
    enable = true;

    # Config is managed by secrets template
    # The template (templates/homebridge.json.j2) is rendered with secrets at activation time
    configPath = "${config.home.homeDirectory}/.homebridge/config.json";

    # Enable camera-ffmpeg plugin
    plugins = with pkgs; [
      homebridge-camera-ffmpeg
    ];
  };
}
